apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
  # List the API port first so that NEO4J_SERVICE_PORT contains this value.
  - protocol: TCP
    name: "mongodb-api"
    port: 27017
    targetPort: 27017
